### ISSUE TITLE
CMS style features for the data browser in the Hasura console

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#4609]
- [x] In Browse rows, for filters we have listed out postgres operators ($gte, $ilike etc). Let’s make readable english terms and the operator in brackets so that anybody can understand it quickly.
- [x] Multi select in Browse Rows https://github.com/hasura/graphql-engine/issues/1739
- [x] Browse rows improvements - https://github.com/hasura/graphql-engine-internal/issues/253
- [x] Rearrange columns in a table with localStorage for easier browsing https://github.com/hasura/graphql-engine/issues/3390
- [x] Accept query params for Browse Rows https://github.com/hasura/graphql-engine/issues/833 to share a page with a particular filtered dataset.
- [x] Simplify adding related data hasura/graphql-engine#3422
- [ ] ~Bug on Insert row https://github.com/hasura/graphql-engine/issues/3332~. - _We can ignore this for now_
- [ ] Show dropdown for relational content during insert row. (For example: If i'm inserting an article, and author_id is a foreign key, show a searchable dropdown with list of authors) hasura/graphql-engine#2296
- [ ]  Widgets for content types https://github.com/hasura/graphql-engine/issues/192
   - Rich text / markdown editor for `text` column type
   - Calendar widget for dates
   - Time picker for time
   - Dropdown for enums
   - JSON editor for JSON/JSONB columns
- [ ] handle bigint type hasura/graphql-engine#3667
- [ ] Form validation hasura/graphql-engine#3728
- [ ] Add support for common fields like email, url hasura/graphql-engine#1862
- [ ] Permission based data viewer (tables / rows / operations)
- [ ] Simplify adding related data hasura/graphql-engine#3422
- [ ] handle bigint type hasura/graphql-engine#3667
- [ ] Form validation hasura/graphql-engine#3728
- [ ] Add support for common fields like email, url hasura/graphql-engine#1862
- [ ] Full-width insert and edit

**Comment by hmexx** [comment]
It might be too late now that so much work has gone into the data viewer, but building on top of a powerful grid widget like tabulator, instead of building a CMS-ey type UI from scratch, might have/be the way to go.

http://tabulator.info/
