### ISSUE TITLE
mysql: tracking issue

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7372]
Query support:

- [ ] tables/views
  - [ ] boolean expressions
  - [ ] ordering
  - [ ] pagination: limit/offset
- [ ] relationships
  - [ ] in boolean expressions
  - [ ] order expressions
- [ ] permissions
- [ ] aggregate queries on tables and relationships

**Comment by sassela** [comment]
@0x777 this looks like a dupe of https://github.com/hasura/project-data-sources/issues/6

**Comment by praveenweb** [comment]
MySQL support is now available via Data Connectors from Hasura v2.19.0. Read the docs here https://hasura.io/docs/latest/databases/mysql/docker/

Closing this issue now.
