### ISSUE TITLE
server/mssql: support `update` mutations

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#7624]
This is incremental work towards [enabling mutations on MSSQL backend](https://github.com/hasura/graphql-engine/issues/7621).

## Goals:
- generate update mutations schema (https://github.com/hasura/graphql-engine-mono/issues/2841)
  - Complete `msBuildTableUpdateMutationFields` function. We should only include the basic `_set` update operator.
  - Able to view update mutations schema for MSSQL tables in API console with permissions enforced
- Update SQL generation / execution
  - An intermediate AST `data Update` that is readily translated to SQL update statement
  - Translation of IR (`AnnUpdate`) to `data Update`

## Sub-issues:

- [ ] https://github.com/hasura/graphql-engine-mono/issues/2678
- [x] https://github.com/hasura/graphql-engine-mono/issues/2741
- [x] https://github.com/hasura/graphql-engine-mono/issues/2795
- [ ] [server: introduce backend-agnostic "column mutability" for mutations](https://github.com/hasura/graphql-engine-mono/issues/2770)
- [x] [server: Implement schema for MSSQL updates](https://github.com/hasura/graphql-engine-mono/issues/2841)
- [x] #7815
- [x] https://github.com/hasura/graphql-engine/issues/7834

The above issues represent work necessary to complete this. [^sub-issues].

[^sub-issues]: However, they do not comprise the sum total of necessary work. They are simply work items that are large enough that it's more convenient to manage them as separate issues.

## Spin-off issues

- https://github.com/hasura/graphql-engine-mono/issues/2746

The above issues are not necessary for an acceptable, basic implementation.

## References:
- `Hasura.Backends.MSSQL.Types.Internal` module for `data Select` AST
- [Microsoft Docs](https://docs.microsoft.com/en-us/sql/t-sql/queries/update-transact-sql?view=sql-server-ver15) for `UPDATE` syntax

**Comment by sassela** [comment]
Closing this, since the last substantial piece of work on update mutations was [merged last week](https://github.com/hasura/graphql-engine/commit/f00404e0f607b761c339cac6d51be850767fcd4e) 🎉
