### ISSUE TITLE
server/tests: port pytests to hspec integration test suite

### ISSUE THREAD

**Issue by sassela** [hasura/graphql-engine#8432]
Relates to https://github.com/hasura/graphql-engine/issues/7760

This is a placeholder for now, for related tests as we think of them. But we might use this to coordinate work to gradually port pytests to hspecs, now that the [POC integration test suite](https://github.com/hasura/graphql-engine/issues/7760) is done. In rough priority order:

- [x] https://github.com/hasura/graphql-engine/issues/8433#issue-1214623537
- [x] [server/tests: organise hspec integration tests to mirror product architecture](https://github.com/hasura/graphql-engine-mono/issues/4757)
- [x] https://github.com/hasura/graphql-engine/issues/8172
- [ ] #8891
- [ ] [BigQuery schema, queries](https://github.com/hasura/graphql-engine-mono/issues/4758)
- [ ] Citus schema, queries, mutations, subscriptions
- [ ] SQL Server schema, queries, mutations, subscriptions
- [ ] remove duplicate Postgres pytests (the goal is _not_ to port over all Postgres pytests, only those testing common backend features)
- [ ] [run hspec tests on ARM](https://github.com/hasura/graphql-engine-mono/issues/3511)
- [ ] [support multitenant tests](https://github.com/hasura/graphql-engine-mono/issues/3680)
- [ ] parallelise test execution (or check it)
- [ ] DB healthcheck
- [ ] [server/bigquery: investigate bigquery API performance improvements](https://github.com/hasura/graphql-engine-mono/issues/3683)

**Comment by sassela** [comment]
> These tests also seem to fail for unrelated reasons quite often in CI

Do you have any recent examples? If so, mind adding them as comments [here](https://github.com/hasura/graphql-engine-mono/issues/4783)? Gil did a bunch of work to stabilise the BQ tests in CI, but I wasn't aware of other recent failures.

> I wonder how much effort is worth to put into improving the failure rate, versus migrating off the test suite entirely.

Good question. I can't speak with any confidence about this until we [_measure_ the success rate in CI](https://github.com/hasura/graphql-engine-mono/issues/5083) 😄 otherwise we're just working with anecdata. I created an issue to discuss at backlog refinement, so we can improve visibility here.

**Comment by sassela** [comment]
Closing this issue in favour of internal JIRA tickets
