### ISSUE TITLE
CockroachDB: Basic query support

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#8788]
Our initial support for `v22.1` CockroachDB should include just that of running basic queries.

The scope of this is that a user should be able to, via the console:
1. Add a cockroachdb source on a page branded as such.
2. Create and track tables
5. Run a graphql query that exercises filters and aggregations.

The following are excluded from the scope of basic queries and can be implemented afterwards:
1. Track object and array relationships
4. Set query permissions
5. Run a graphql query that exercises relationships.

In order for the GraphQL-Engine to be able to support this, the following gaps need to be closed (to be made into separate issues):

General infrastructure:
- [x] hasura/graphql-engine#8789
- [x] hasura/graphql-engine#8839
- [x] hasura/graphql-engine#8891

On the server side:
- [x] hasura/graphql-engine#8790 
- [x] hasura/graphql-engine#8800
- [x] hasura/graphql-engine-mono#5593
- [x] hasura/graphql-engine#8791 
- [x] hasura/graphql-engine#8840
- [x] hasura/graphql-engine#8797
- [x] hasura/graphql-engine#8799
- [x] hasura/graphql-engine#8792 
- [x] hasura/graphql-engine#8890

On the console side:
- [x] hasura/graphql-engine#8793 
- [x] hasura/graphql-engine#8794 
- [x] hasura/graphql-engine-mono#5567

Docs:
- [x] #9021
- [x] #9018

Incoming support/fixes from CRDB team (in rough priority order):
- [x] https://github.com/cockroachdb/cockroach/issues/86375
- [x] https://github.com/cockroachdb/cockroach/pull/87535
- [x] https://github.com/cockroachdb/cockroach/issues/87481
- [x] hasura/graphql-engine#8821
- [x] https://github.com/hasura/graphql-engine-mono/issues/5984
- [x] https://github.com/cockroachdb/cockroach/issues/87947
- [ ] https://github.com/cockroachdb/cockroach/issues/83255

**Comment by sassela** [comment]
just added https://github.com/hasura/graphql-engine/issues/8891 to this list, which we'll estimate  later

**Comment by sassela** [comment]
Released in [v2.15.0](https://hasura.io/changelog/community-edition/v2.15.0)! Closing
